###
GET http://localhost:3070/

###
GET http://localhost:3070/localhost:3070/api/v1/exercises?page=2&pageSize=30

###
POST http://localhost:3070/api/v1/exercises/64418de0f09282c0f7970ba7

###
POST http://localhost:3070/api/v1/exercises
Content-Type: application/json
some-other-header: with my very own personal information

{
  "userId": 1,
  "userName": "Viri Marin ",
  "handle": "@virimarin",
  "name": "Biked through campus",
  "date": "03/20/2023",
  "duration": "1 hour",
  "location": "New Paltz",
  "picture": "http://t3.gstatic.com/licensed-image?q=tbn:ANd9GcTTmrxYuiGmw6nmOCKjjSHdtRWLq6Upml3Kb__p9ihakdUwUoxVYKfi4GD5X52Us0X1",
  "type": "bike"
}

###
PATCH http://localhost:3070/api/v1/exercises
Content-Type: application/json
some-other-headerz: with ,y very own personal information

{
  "_id": "64418ffa4925ec04c2c37dd0",
  "userId": 1,
  "name": "Biked through campus"
}

###
DELETE http://localhost:3070/api/v1/exercises/64418de0f09282c0f7970ba7

###
GET  http://localhost:3070/api/v1/exercises/search/biked

###
POST http://localhost:3070/api/v1/exercises/seed