@port=3070
@jwt={{login.response.body.data.token}}
###
GET http://localhost:{{port}}/

###
GET http://localhost:{{port}}/api/v1/exercises?page=2&pageSize=30
Authorization: Bearer {{jwt}}

###
POST http://localhost:{{port}}/api/v1/exercises/64418de0f09282c0f7970ba7

###
POST http://localhost:{{port}}/api/v1/exercises
Content-Type: application/json
some-other-header: with my very own personal information

{
  "userId": 1,
  "userName": "Viri Marin ",
  "handle": "@virimarin",
  "name": "Biked through campus",
  "date": "03/20/2023",
  "duration": "1 hour",
  "location": "New Paltz",
  "picture": "http://t3.gstatic.com/licensed-image?q=tbn:ANd9GcTTmrxYuiGmw6nmOCKjjSHdtRWLq6Upml3Kb__p9ihakdUwUoxVYKfi4GD5X52Us0X1",
  "type": "bike"
}

###
PATCH http://localhost:{{port}}/api/v1/exercises
Content-Type: application/json
some-other-headerz: with ,y very own personal information

{
  "_id": "64418ffa4925ec04c2c37dd0",
  "userId": 1,
  "name": "Biked through campus"
}

###
DELETE http://localhost:{{port}}/api/v1/exercises/644dca6c68977b0d928be539
###
GET  http://localhost:{{port}}/api/v1/exercises/search/cardio


###
POST http://localhost:{{port}}/api/v1/exercises/seed

###
POST http://localhost:{{port}}/api/v1/users/seed

###
GET http://localhost:{{port}}/api/v1/users
Content-Type: application/json

###
GET http://localhost:{{port}}/api/v1/users

###
GET http://localhost:{{port}}/api/v1/exercises

###
# @name login
POST http://localhost:{{port}}/api/v1/users/login
Content-Type: application/json

{
  "email": "marinherv1@newpaltz.edu",
  "password": "password"
}

###
# @name login
POST http://localhost:{{port}}/api/v1/users/login
Content-Type: application/json

{
  "email": "jsmith@gmail.com",
  "password": "password11"
}


###
# @name login
POST http://localhost:{{port}}/api/v1/users/login
Content-Type: application/json

{
  "email": "lucymartinez@hotmail.com",
  "password": "password12"
}